import type { Metadata } from 'next'
import { Fira_Mono } from 'next/font/google'
import './globals.css'

const firaMono = Fira_Mono({
	variable: '--font-fira-mono',
	weight: ['400', '500', '700'],
	preload: true,
	subsets: ['latin', 'cyrillic']
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" className={`${firaMono.variable}`}>
			<body className={`h-screen w-screen antialiased`}>{children}</body>
		</html>
	)
}
